.PHONY: all asm c zig rust

all: c rust

asm:
	@cd asm; \
	make run ARGS=../input.txt

c:
	@cd C; \
	make run ARGS=../input.txt

zig:
	@cd zig; \
	make run ARGS=../input.txt

rust:
	@cd rust; \
	make run ARGS=../input.txt
